# Generated by Django 5.1.1 on 2024-10-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coworking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('capacidad', models.IntegerField()),
                ('precio_por_hora', models.DecimalField(decimal_places=2, max_digits=6)),
                ('disponibilidad', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Auto',
        ),
    ]
